server:
  http_listen_port: 8080

logging:
  level: info

positions:
  filename: /var/log/alloy-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'mqtt_honeypot'
    static_configs:
      - targets:
          - localhost
        labels:
          job: mqtt_honeypot
          application: mqtt_honeypot
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            msg: message
      - labels:
          level:
          msg:
    file_sd_configs:
      - files:
          - /usr/src/app/mqtt_honeypot_logs/mqtt_honeypot.log
